<?php

namespace Web\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PlaceInstallationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaceInstallationRepository extends EntityRepository
{
}
