<?php

namespace Web\AssetsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AssetsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssetsRepository extends EntityRepository
{
}
