<?php

namespace Web\AmortizationBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AmortizationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AmortizationRepository extends EntityRepository {

    function getAmortizationsMoreThen($num = 0) {

        $em = $this->getEntityManager();

        $query = $em->createQuery(
                        'SELECT amort
                         FROM WebAmortizationBundle:Amortization amort
                         WHERE amort.amortization > :amortization
                         ORDER BY amort.amortization ASC'
                )->setParameter('amortization', $num);

        return $query->getResult();
    }

    function getAmortizationsMoreThenAlgTwo($num = 0) {

        $em = $this->getEntityManager();
        $repository = $em->getRepository('WebAmortizationBundle:Amortization');

        $query = $repository->createQueryBuilder('amort')
                ->where('amort.amortization > :amortization')
                ->setParameter('amortization', $num)
                ->orderBy('amort.amortization', 'ASC')
                ->getQuery();

        return $query->getResult();
    }

    function getAllOderByPeriodDesc() {
        return $this->getEntityManager()
                        ->createQuery(
                                'SELECT amort '
                                . 'FROM WebAmortizationBundle:Amortization amort '
                                . 'ORDER BY amort.period DESC'
                        )
                        ->getResult();
    }

    function getAmortizationsByAsertId($id = 1) {

        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT amort, a FROM WebAmortizationBundle:Amortization amort
                                   JOIN amort.aset a
                                   WHERE a.id = :id")
                ->setParameter('id', $id);

        return $query->getResult();
    }

    function Test($id = 1) {

        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT amort, a FROM WebAmortizationBundle:Amortization amort
                                   JOIN WebAmortizationBundle:Categories a
                                   WHERE  
                                        amort.id = a.id 
                                        ");
                                    //->setParameter('id', $id);
        /*
        $query = $em->createQuery("SELECT amort, a FROM WebAmortizationBundle:Amortization amort
                                   JOIN WebAssetsBundle:Assets a
                                   WHERE                                         
                                        a.id = :id")
                ->setParameter('id', $id);*/
        
        return $query->getResult();
    }

}
