<?php

namespace Web\AmortizationBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AmortizationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AmortizationRepository extends EntityRepository
{
}
