
web_amortization:
    resource: "@WebAmortizationBundle/Resources/config/routing.yml"

web_assets:
    resource: "@WebAssetsBundle/Resources/config/routing.yml"
    prefix:   /

web_cities:
    resource: "@WebCitiesBundle/Resources/config/routing.yml"
    prefix:   /

web_security:
    resource: "@WebSecurityBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: "@WebAdminBundle/Resources/config/routing.yml"
    prefix:
