# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Web\SecurityBundle\Entity\User:
            algorithm: bcrypt
            cost: 5

    providers:
        chain_provider:
            chain:
                providers: [loyd_db_provider]
        loyd_db_provider:
            entity:
                class: WebSecurityBundle:User
                property: username

    role_hierarchy:
        ROLE_TEAM:        ROLE_USER
        ROLE_OPERATOR:    ROLE_USER
        ROLE_ADMIN:       [ROLE_TEAM,ROLE_OPERATOR]
        ROLE_ROOT:        [ROLE_ADMIN,ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            provider: db_provider1

        main:
            anonymous: ~
            form_login:
                login_path: web_security_login
                check_path: web_security_login_check
            logout:
                path: web_security_logout
                invalidate_session: true
                target: web_security_login

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
