admin_users_index:
    path:     /{_locale}
    defaults: { _controller: "WebAdminBundle:User:index" }
    methods:  GET
    requirements:
        _locale: en|fr|ua

admin_users_show:
    path:     /show/{id}
    defaults: { _controller: "WebAdminBundle:User:show" }
    methods:  GET

admin_users_new:
    path:     /new
    defaults: { _controller: "WebAdminBundle:User:new" }
    methods:  [GET, POST]

admin_users_edit:
    path:     /edit/{id}
    defaults: { _controller: "WebAdminBundle:User:edit" }
    methods:  [GET, POST]

admin_users_delete:
    path:     /delete/{id}
    defaults: { _controller: "WebAdminBundle:User:delete" }
    methods:  [GET]
