loyd_admin_homepage:
    path:     /admin
    defaults: { _controller: WebAdminBundle:Admin:index }
#loyd_admin_login:
#        path:     /login
#        defaults: { _controller: AdminBundle:Default:login }

web_admin_users:
    resource: "@WebAdminBundle/Resources/config/routing/user.yml"
    prefix:   /admin/users
