amortization_index:
    path:     /
    defaults: { _controller: "WebAmortizationBundle:Amortization:index" }
    methods:  GET

amortization_show:
    path:     /{id}/show
    defaults: { _controller: "WebAmortizationBundle:Amortization:show" }
    methods:  GET

amortization_new:
    path:     /new
    defaults: { _controller: "WebAmortizationBundle:Amortization:new" }
    methods:  [GET, POST]

amortization_edit:
    path:     /{id}/edit
    defaults: { _controller: "WebAmortizationBundle:Amortization:edit" }
    methods:  [GET, POST]

amortization_delete:
    path:     /{id}/delete
    defaults: { _controller: "WebAmortizationBundle:Amortization:delete" }
    methods:  GET
