tests_dql:
    path:     /dql/{_locale}
    defaults: { _controller: "WebAmortizationBundle:Tests:dql" }
    methods:  GET
    requirements:
        _locale: en|fr|ua

tests_array:
    path:     /array/
    defaults: { _controller: "WebAmortizationBundle:Tests:array" }
    methods:  GET     
        

tests_lng:
    path:     /lng/{_locale}
    defaults: { _controller: "WebAmortizationBundle:Tests:lng" }
    methods:  GET   
    requirements:
        _locale: en|fr|ua