web_security_login:
    path:     /login
    defaults: { _controller: WebSecurityBundle:Login:login }

web_security_login_check:
    path:     /login_check
    defaults: { _controller: WebSecurityBundle:Login:login_check }

web_security_logout:
    path:     /logout
    defaults: { _controller: WebSecurityBundle:Login:logout }
